#pragma once

#include <QList>
#include <QString>

struct ExamQuestion {
    QString subject;
    QString difficulty;
    QString text;
    QString optionA;
    QString optionB;
    QString optionC;
    QString optionD;
    int correctAnswer;
};

static const QList<ExamQuestion> QUESTIONS_BANK = {
    { "English", "Beginner", "Which word is a noun?", "Quickly", "Blue", "Teacher", "Under", 2 },
    { "English", "Beginner", "Choose the correct plural form.", "Childs", "Children", "Childes", "Childrens", 1 },
    { "English", "Beginner", "Which sentence uses correct punctuation?", "Hello how are you", "Hello, how are you?", "Hello how are you?", "Hello, how are you", 1 },
    { "English", "Beginner", "Select the verb in this sentence: Birds fly high.", "Birds", "Fly", "High", "This", 1 },
    { "English", "Beginner", "What is the opposite of cold?", "Warm", "Wet", "Dark", "Soft", 0 },
    { "English", "Beginner", "Which is a synonym of happy?", "Sad", "Angry", "Joyful", "Tired", 2 },
    { "English", "Beginner", "Which word is a pronoun?", "Run", "He", "Blue", "Table", 1 },
    { "English", "Beginner", "Choose the correct article: ___ apple", "A", "An", "The", "No article", 1 },
    { "English", "Beginner", "Which word is a verb?", "Jump", "Mountain", "Green", "Window", 0 },
    { "English", "Beginner", "What is the plural of box?", "Boxs", "Boxes", "Boxeses", "Boxen", 1 },
    { "English", "Beginner", "Which sentence is correct?", "She go to school.", "She goes to school.", "She going to school.", "She gone to school.", 1 },
    { "English", "Beginner", "Choose the antonym of big.", "Large", "Huge", "Small", "Wide", 2 },
    { "English", "Beginner", "Which word names a place?", "City", "Quickly", "Red", "Sing", 0 },
    { "English", "Beginner", "Which is a complete sentence?", "Running fast.", "The happy dog.", "They are playing.", "Because it rained.", 2 },
    { "English", "Beginner", "Choose the correct capitalization.", "london is a city.", "London is a city.", "London Is a city.", "london Is a City.", 1 },
    { "English", "Beginner", "Which mark ends a question?", "Period", "Comma", "Question mark", "Colon", 2 },
    { "English", "Beginner", "Select the adjective.", "Beautiful", "Slowly", "Dance", "River", 0 },
    { "English", "Beginner", "What is the past tense of walk?", "Walked", "Walking", "Walks", "Walk", 0 },
    { "English", "Beginner", "Choose the correct word: two ___", "cat", "cats", "cat's", "cates", 1 },
    { "English", "Beginner", "Which word is a conjunction?", "And", "Book", "Happy", "Under", 0 },

    { "English", "Intermediate", "Identify the adjective in: The ancient castle stood silent.", "Castle", "Stood", "Ancient", "Silently", 2 },
    { "English", "Intermediate", "Choose the correctly spelled word.", "Definately", "Definitely", "Definitly", "Definetely", 1 },
    { "English", "Intermediate", "Which sentence is in passive voice?", "The chef cooked dinner.", "Dinner was cooked by the chef.", "The chef is cooking dinner.", "The chef cooks dinner.", 1 },
    { "English", "Intermediate", "What is the main purpose of a thesis statement?", "To ask a question", "To summarize sources", "To present the main argument", "To list references", 2 },
    { "English", "Intermediate", "Choose the correct conjunction: I stayed home ___ it was raining.", "because", "unless", "although", "if", 0 },
    { "English", "Intermediate", "Which sentence has correct subject-verb agreement?", "The team are winning.", "The team is winning.", "The team were winning.", "The team have won.", 1 },
    { "English", "Intermediate", "Choose the sentence with correct comma usage.", "After school we went home.", "After school, we went home.", "After, school we went home.", "After school we, went home.", 1 },
    { "English", "Intermediate", "Which is a complex sentence?", "I read and wrote.", "I read because I had homework.", "Read the chapter.", "The tall tree.", 1 },
    { "English", "Intermediate", "Pick the correct transition word for contrast.", "Therefore", "However", "Finally", "Similarly", 1 },
    { "English", "Intermediate", "Which word is an adverb?", "Quickly", "Quick", "Speed", "Runner", 0 },
    { "English", "Intermediate", "Choose the correctly punctuated quote.", "She said I am ready.", "She said, I am ready.", "She said, \"I am ready.\"", "She said \"I am ready\".", 2 },
    { "English", "Intermediate", "What does summarize mean?", "Add new ideas", "Retell main points briefly", "Copy every sentence", "Argue against text", 1 },
    { "English", "Intermediate", "Choose the sentence in past perfect tense.", "She had finished before noon.", "She finishes at noon.", "She is finishing now.", "She will finish tomorrow.", 0 },
    { "English", "Intermediate", "Which sentence is formal writing?", "Kids gotta learn stuff.", "Students must acquire knowledge.", "School's kinda hard.", "We ain't done yet.", 1 },
    { "English", "Intermediate", "Select the correct pronoun: Each student must bring ___ notebook.", "their", "his or her", "our", "your", 1 },
    { "English", "Intermediate", "Which is the best topic sentence?", "There are many things.", "Recycling reduces waste and protects natural resources.", "I like pizza.", "Books are made of paper.", 1 },
    { "English", "Intermediate", "Choose the sentence with proper parallelism.", "She likes to read, to paint, and cooking.", "She likes reading, painting, and cooking.", "She likes read, paint, and cooking.", "She likes to reading, paint, and cook.", 1 },
    { "English", "Intermediate", "What is the function of a conclusion paragraph?", "Introduce topic", "Provide evidence", "Wrap up main ideas", "Define terms", 2 },
    { "English", "Intermediate", "Choose the correct possessive form.", "The dogs bone", "The dog's bone", "The dogs' bone", "Dog'ss bone", 1 },
    { "English", "Intermediate", "Which sentence avoids a run-on?", "I was late I missed the bus.", "I was late, I missed the bus.", "I was late, so I missed the bus.", "I was late so, I missed the bus.", 2 },

    { "English", "Advanced", "What literary device is used in: Time is a thief?", "Simile", "Hyperbole", "Metaphor", "Alliteration", 2 },
    { "English", "Advanced", "Choose the sentence with correct parallel structure.", "She likes reading, to swim, and biking.", "She likes reading, swimming, and biking.", "She likes to read, swimming, and biking.", "She likes read, swim, and biking.", 1 },
    { "English", "Advanced", "What does juxtaposition mean in literature?", "Using exaggerated statements", "Placing contrasting ideas together", "Repeating consonant sounds", "A direct comparison using like/as", 1 },
    { "English", "Advanced", "Which sentence uses a semicolon correctly?", "I studied hard; and I passed.", "I studied hard; I passed.", "I studied; hard I passed.", "I studied hard I; passed.", 1 },
    { "English", "Advanced", "In rhetoric, ethos primarily appeals to:", "Emotion", "Logic", "Credibility", "Humor", 2 },
    { "English", "Advanced", "Which phrase is an oxymoron?", "Bittersweet", "As brave as a lion", "The wind whispered", "A flood of tears", 0 },
    { "English", "Advanced", "Which rhetorical appeal targets logic?", "Ethos", "Pathos", "Logos", "Kairos", 2 },
    { "English", "Advanced", "What is dramatic irony?", "Characters know more than audience", "Audience knows more than characters", "A sudden plot twist", "A repeated phrase", 1 },
    { "English", "Advanced", "Choose the best example of allusion.", "He was a giant in class.", "She ran like the wind.", "He met his Waterloo in the finals.", "The leaves danced.", 2 },
    { "English", "Advanced", "Which sentence has correct subjunctive mood?", "If I was you, I'd go.", "If I were you, I'd go.", "If I am you, I'd go.", "If I be you, I'd go.", 1 },
    { "English", "Advanced", "What is anaphora?", "Repetition at sentence beginnings", "A story's climax", "A hidden comparison", "A rhyme pattern", 0 },
    { "English", "Advanced", "Which statement is the strongest thesis?", "Pollution is bad.", "This essay talks about pollution.", "Cities should expand public transit to cut urban air pollution.", "Many people think things.", 2 },
    { "English", "Advanced", "Identify the sentence with correct colon use.", "She bought: apples, bread, and milk.", "She bought apples: bread, and milk.", "She bought the essentials: apples, bread, and milk.", "She: bought apples, bread, and milk.", 2 },
    { "English", "Advanced", "What does concise writing prioritize?", "Longer sentences", "Clarity with fewer words", "More adjectives", "Complex punctuation", 1 },
    { "English", "Advanced", "Choose the best revision for formal tone.", "The results are kind of bad.", "The results are suboptimal.", "The results are super bad.", "The results are pretty rough.", 1 },
    { "English", "Advanced", "Which is an example of metonymy?", "The White House issued a statement.", "Her smile was sunshine.", "Time crawled by.", "He fought like a lion.", 0 },
    { "English", "Advanced", "What is the purpose of a counterargument in an essay?", "Ignore opposition", "Strengthen argument by addressing opposing views", "Add unrelated detail", "End introduction", 1 },
    { "English", "Advanced", "Choose the sentence with proper modifier placement.", "Running quickly, the finish line was crossed by Mia.", "Mia crossed the finish line running quickly.", "The finish line, running quickly, Mia crossed.", "Running quickly crossed Mia the finish line.", 1 },
    { "English", "Advanced", "Which is an objective statement?", "This novel is boring.", "The novel has 12 chapters.", "The hero is amazing.", "The ending is terrible.", 1 },
    { "English", "Advanced", "What is polysyndeton?", "Omitting conjunctions", "Repeating conjunctions for effect", "Using only one conjunction", "Replacing conjunctions with commas", 1 },

    { "Math", "Beginner", "What is 9 + 7?", "14", "15", "16", "17", 2 },
    { "Math", "Beginner", "What is 6 × 8?", "42", "46", "48", "56", 2 },
    { "Math", "Beginner", "What is 45 ÷ 5?", "8", "9", "10", "11", 1 },
    { "Math", "Beginner", "Which number is even?", "21", "33", "48", "57", 2 },
    { "Math", "Beginner", "What is the value of 3²?", "6", "8", "9", "12", 2 },
    { "Math", "Beginner", "Solve: 100 - 37", "63", "67", "73", "57", 0 },
    { "Math", "Beginner", "What is 12 + 15?", "25", "26", "27", "28", 2 },
    { "Math", "Beginner", "What is 7 × 6?", "36", "40", "42", "48", 2 },
    { "Math", "Beginner", "What is 81 ÷ 9?", "7", "8", "9", "10", 2 },
    { "Math", "Beginner", "What is 14 - 9?", "3", "4", "5", "6", 2 },
    { "Math", "Beginner", "Which number is odd?", "24", "38", "41", "52", 2 },
    { "Math", "Beginner", "What is 5²?", "10", "15", "20", "25", 3 },
    { "Math", "Beginner", "What is half of 50?", "20", "25", "30", "35", 1 },
    { "Math", "Beginner", "What is 30 + 19?", "47", "48", "49", "50", 2 },
    { "Math", "Beginner", "What is 90 - 45?", "35", "40", "45", "50", 2 },
    { "Math", "Beginner", "Which is greater?", "17", "19", "Both equal", "Cannot compare", 1 },
    { "Math", "Beginner", "What is 4 × 11?", "40", "42", "44", "46", 2 },
    { "Math", "Beginner", "What is 64 ÷ 8?", "6", "7", "8", "9", 2 },
    { "Math", "Beginner", "What is 18 + 7?", "24", "25", "26", "27", 1 },
    { "Math", "Beginner", "What is 13 - 6?", "5", "6", "7", "8", 2 },

    { "Math", "Intermediate", "Solve: 3x + 5 = 20", "x = 3", "x = 4", "x = 5", "x = 6", 2 },
    { "Math", "Intermediate", "What is 20% of 150?", "25", "30", "35", "40", 1 },
    { "Math", "Intermediate", "Find the area of a rectangle (length 8, width 5).", "13", "26", "40", "45", 2 },
    { "Math", "Intermediate", "Simplify: 2(3a - 4)", "6a - 4", "6a - 8", "5a - 8", "6a + 8", 1 },
    { "Math", "Intermediate", "What is the next prime after 11?", "12", "13", "15", "17", 1 },
    { "Math", "Intermediate", "If y = 2x and x = 7, what is y?", "9", "12", "14", "16", 2 },
    { "Math", "Intermediate", "Solve: 4x - 3 = 17", "x = 4", "x = 5", "x = 6", "x = 7", 1 },
    { "Math", "Intermediate", "What is 15% of 200?", "20", "25", "30", "35", 2 },
    { "Math", "Intermediate", "Perimeter of a square with side 9 is:", "18", "27", "36", "81", 2 },
    { "Math", "Intermediate", "Simplify: 5a + 2a - 3", "7a - 3", "7a + 3", "3a - 3", "5a - 1", 0 },
    { "Math", "Intermediate", "What is the median of 3, 5, 9, 11, 15?", "5", "7", "9", "11", 2 },
    { "Math", "Intermediate", "Convert 0.75 to a fraction.", "1/2", "2/3", "3/4", "4/5", 2 },
    { "Math", "Intermediate", "Solve: x/3 = 8", "x = 11", "x = 21", "x = 24", "x = 27", 2 },
    { "Math", "Intermediate", "What is the slope of line through (0,0) and (2,6)?", "1", "2", "3", "4", 2 },
    { "Math", "Intermediate", "Evaluate: 2^4 + 3", "16", "17", "18", "19", 3 },
    { "Math", "Intermediate", "What is 7/10 as a percent?", "7%", "70%", "0.7%", "700%", 1 },
    { "Math", "Intermediate", "Solve: 9 + 2x = 25", "x = 6", "x = 7", "x = 8", "x = 9", 2 },
    { "Math", "Intermediate", "If a triangle has angles 50° and 60°, third angle is:", "60°", "70°", "80°", "90°", 1 },
    { "Math", "Intermediate", "Simplify: (a^2)(a^3)", "a^5", "a^6", "a^8", "2a^5", 0 },
    { "Math", "Intermediate", "Mean of 4, 8, 10 is:", "6", "7", "7.33", "8", 2 },

    { "Math", "Advanced", "If f(x) = x² - 3x + 2, what is f(4)?", "4", "6", "8", "10", 1 },
    { "Math", "Advanced", "Solve: 2x² = 50", "x = ±5", "x = ±10", "x = 5", "x = 10", 0 },
    { "Math", "Advanced", "What is the derivative of x³?", "x²", "2x", "3x²", "3x", 2 },
    { "Math", "Advanced", "The sum of interior angles of a hexagon is:", "540°", "600°", "720°", "900°", 2 },
    { "Math", "Advanced", "Which is the correct quadratic formula denominator?", "2a", "a", "b", "2b", 0 },
    { "Math", "Advanced", "Solve the system: x + y = 10, x - y = 2", "x=4, y=6", "x=5, y=5", "x=6, y=4", "x=7, y=3", 2 },
    { "Math", "Advanced", "Derivative of 5x^4 is:", "20x^3", "5x^3", "4x^5", "20x^4", 0 },
    { "Math", "Advanced", "Integral of 2x dx is:", "x^2 + C", "2x + C", "x + C", "x^3 + C", 0 },
    { "Math", "Advanced", "If log10(1000) = ?", "2", "3", "4", "10", 1 },
    { "Math", "Advanced", "Solve: x^2 - 9 = 0", "x = 9", "x = -9", "x = ±3", "x = ±9", 2 },
    { "Math", "Advanced", "Matrix multiplication is possible when:", "Rows are equal", "Columns are equal", "Inner dimensions match", "Outer dimensions match", 2 },
    { "Math", "Advanced", "What is sin(90°)?", "0", "1", "-1", "Undefined", 1 },
    { "Math", "Advanced", "Limit of (1/x) as x approaches infinity is:", "1", "0", "Infinity", "Does not exist", 1 },
    { "Math", "Advanced", "For arithmetic sequence 2,5,8,... the 10th term is:", "27", "29", "30", "32", 1 },
    { "Math", "Advanced", "Determinant of [[1,2],[3,4]] is:", "-2", "2", "10", "-10", 0 },
    { "Math", "Advanced", "If |x| = 7, possible x values are:", "7 only", "-7 only", "-7 and 7", "0 and 7", 2 },
    { "Math", "Advanced", "Solve: e^x = 1", "x = 0", "x = 1", "x = e", "x = -1", 0 },
    { "Math", "Advanced", "Standard deviation measures:", "Center", "Spread", "Skew", "Count", 1 },
    { "Math", "Advanced", "If vectors are perpendicular, their dot product is:", "1", "-1", "0", "Undefined", 2 },
    { "Math", "Advanced", "Complex number i^2 equals:", "1", "-1", "i", "-i", 1 },

    { "History", "Beginner", "In which year did World War I begin?", "1912", "1914", "1916", "1918", 1 },
    { "History", "Beginner", "Who was the first person on the Moon?", "Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn", 1 },
    { "History", "Beginner", "The Great Wall is in which country?", "India", "Japan", "China", "Korea", 2 },
    { "History", "Beginner", "Who discovered America in 1492 (traditional answer)?", "Magellan", "Columbus", "Cook", "Vespucci", 1 },
    { "History", "Beginner", "Which civilization built pyramids at Giza?", "Roman", "Greek", "Egyptian", "Persian", 2 },
    { "History", "Beginner", "The Berlin Wall fell in:", "1987", "1988", "1989", "1991", 2 },
    { "History", "Beginner", "Who was known as the Maid of Orleans?", "Cleopatra", "Joan of Arc", "Queen Victoria", "Catherine the Great", 1 },
    { "History", "Beginner", "Which ocean did Columbus cross in 1492?", "Indian", "Pacific", "Atlantic", "Arctic", 2 },
    { "History", "Beginner", "Ancient Rome is located in modern:", "Spain", "Italy", "France", "Greece", 1 },
    { "History", "Beginner", "Who built the Taj Mahal?", "Akbar", "Shah Jahan", "Aurangzeb", "Babur", 1 },
    { "History", "Beginner", "The first president of the USA was:", "Lincoln", "Jefferson", "Washington", "Adams", 2 },
    { "History", "Beginner", "Which country gave the Statue of Liberty to the USA?", "Germany", "France", "Italy", "Canada", 1 },
    { "History", "Beginner", "The Titanic sank in:", "1905", "1912", "1918", "1923", 1 },
    { "History", "Beginner", "The pyramids of Giza are in:", "Peru", "Mexico", "Egypt", "Iraq", 2 },
    { "History", "Beginner", "Who was the first man in space?", "Neil Armstrong", "Yuri Gagarin", "John Glenn", "Valentina Tereshkova", 1 },
    { "History", "Beginner", "The Roman numeral X means:", "5", "10", "50", "100", 1 },
    { "History", "Beginner", "Which war ended in 1945?", "WWI", "WWII", "Korean War", "Vietnam War", 1 },
    { "History", "Beginner", "Where were the Olympic Games first held (ancient)?", "Athens", "Olympia", "Sparta", "Rome", 1 },
    { "History", "Beginner", "Who painted the Mona Lisa?", "Michelangelo", "Raphael", "Da Vinci", "Donatello", 2 },
    { "History", "Beginner", "The Cold War was mainly between USA and:", "China", "Germany", "Soviet Union", "Japan", 2 },

    { "History", "Intermediate", "Which document limited the power of King John in 1215?", "Bill of Rights", "Magna Carta", "Treaty of Versailles", "Code of Hammurabi", 1 },
    { "History", "Intermediate", "Which empire conquered Constantinople in 1453?", "Roman", "Ottoman", "Mongol", "Byzantine", 1 },
    { "History", "Intermediate", "Who led the Soviet Union for most of WWII?", "Lenin", "Khrushchev", "Stalin", "Trotsky", 2 },
    { "History", "Intermediate", "The Renaissance began in which region?", "Scandinavia", "Iberia", "Italy", "Balkans", 2 },
    { "History", "Intermediate", "What was the primary goal of the League of Nations?", "Trade expansion", "Colonialism", "Prevent future wars", "Religious unity", 2 },
    { "History", "Intermediate", "Who was the British Prime Minister during most of WWII?", "Attlee", "Churchill", "Eden", "Chamberlain", 1 },
    { "History", "Intermediate", "Which revolution began in France in 1789?", "Industrial", "French", "Russian", "Glorious", 1 },
    { "History", "Intermediate", "Who wrote the Communist Manifesto with Engels?", "Lenin", "Marx", "Stalin", "Trotsky", 1 },
    { "History", "Intermediate", "The unification of Germany was completed in:", "1871", "1815", "1919", "1945", 0 },
    { "History", "Intermediate", "Which empire ruled India before independence in 1947?", "French", "Dutch", "British", "Portuguese", 2 },
    { "History", "Intermediate", "The Battle of Hastings occurred in:", "1066", "1215", "1415", "1660", 0 },
    { "History", "Intermediate", "Who was known as the Sun King?", "Louis XIV", "Napoleon", "Charlemagne", "Henry VIII", 0 },
    { "History", "Intermediate", "The Industrial Revolution began first in:", "France", "Germany", "Britain", "USA", 2 },
    { "History", "Intermediate", "What year did the US Civil War begin?", "1859", "1861", "1863", "1865", 1 },
    { "History", "Intermediate", "Who issued the Edict of Milan in 313 CE?", "Augustus", "Constantine", "Nero", "Trajan", 1 },
    { "History", "Intermediate", "The Meiji Restoration took place in:", "China", "Japan", "Korea", "Vietnam", 1 },
    { "History", "Intermediate", "Which treaty ended World War I?", "Paris", "Versailles", "Vienna", "Tordesillas", 1 },
    { "History", "Intermediate", "Who was the first female Prime Minister of the UK?", "Theresa May", "Margaret Thatcher", "Indira Gandhi", "Golda Meir", 1 },
    { "History", "Intermediate", "The Silk Road connected China mainly with:", "Africa", "Europe", "Australia", "Arctic", 1 },
    { "History", "Intermediate", "Who was assassinated in Sarajevo in 1914?", "Kaiser Wilhelm II", "Tsar Nicholas II", "Archduke Franz Ferdinand", "Otto von Bismarck", 2 },

    { "History", "Advanced", "Which event directly triggered the start of WWI?", "Sinking of Lusitania", "Invasion of Poland", "Assassination of Archduke Franz Ferdinand", "Russian Revolution", 2 },
    { "History", "Advanced", "What was the significance of the Treaty of Westphalia (1648)?", "Ended Napoleonic wars", "Established modern state sovereignty", "Created NATO", "Unified Germany", 1 },
    { "History", "Advanced", "Which empire controlled much of Southeast Europe before WWI?", "Austro-Hungarian", "Ottoman", "Russian", "British", 1 },
    { "History", "Advanced", "Which battle is often seen as the turning point on the Eastern Front in WWII?", "Kursk", "Moscow", "Stalingrad", "Berlin", 2 },
    { "History", "Advanced", "What was the policy of appeasement in the 1930s mainly associated with?", "The US and Japan", "Britain and France toward Nazi Germany", "Soviet expansion", "Italian unification", 1 },
    { "History", "Advanced", "Decolonization in Africa accelerated mostly after:", "World War I", "The Great Depression", "World War II", "The Cold War ended", 2 },
    { "History", "Advanced", "The Thirty Years' War ended with which treaty?", "Treaty of Utrecht", "Peace of Westphalia", "Treaty of Paris", "Treaty of Ghent", 1 },
    { "History", "Advanced", "Which historian wrote The History of the Peloponnesian War?", "Herodotus", "Plutarch", "Thucydides", "Tacitus", 2 },
    { "History", "Advanced", "Realpolitik is most associated with which statesman?", "Metternich", "Bismarck", "Churchill", "De Gaulle", 1 },
    { "History", "Advanced", "The Great Schism of 1054 divided:", "Catholic and Orthodox Churches", "Sunni and Shia Islam", "Judaism and Christianity", "Protestant and Catholic Churches", 0 },
    { "History", "Advanced", "Which conference set post-WWII spheres in Europe in 1945?", "Bandung", "Yalta", "Potsdam only", "Locarno", 1 },
    { "History", "Advanced", "The term ancien regime refers primarily to pre-revolutionary:", "Russia", "France", "Prussia", "Austria", 1 },
    { "History", "Advanced", "Which event marked the start of the Protestant Reformation in 1517?", "Diet of Worms", "95 Theses", "Council of Trent", "Peace of Augsburg", 1 },
    { "History", "Advanced", "Containment as US strategy is linked to:", "Truman Doctrine", "Monroe Doctrine", "Open Door Policy", "Marshall Plan only", 0 },
    { "History", "Advanced", "The Congress of Vienna (1815) aimed mainly to:", "Spread nationalism", "Restore balance of power", "End colonialism", "Create the UN", 1 },
    { "History", "Advanced", "Which dynasty ruled China during most of the 19th century?", "Ming", "Qing", "Han", "Song", 1 },
    { "History", "Advanced", "The term glasnost is associated with reforms by:", "Brezhnev", "Gorbachev", "Yeltsin", "Andropov", 1 },
    { "History", "Advanced", "Which empire fell in 1453 with Constantinople's capture?", "Holy Roman", "Byzantine", "Persian", "Mughal", 1 },
    { "History", "Advanced", "The Haitian Revolution was led by:", "Simon Bolivar", "Toussaint Louverture", "Jean-Paul Marat", "Maximilien Robespierre", 1 },
    { "History", "Advanced", "Which document established human rights norms in 1948?", "UN Charter", "Universal Declaration of Human Rights", "Geneva Convention I", "NATO Treaty", 1 },
};
